#syntax=docker/dockerfile:1.3
FROM --platform=$BUILDPLATFORM alpine AS build
RUN apk add build-base curl git openssh-client
WORKDIR /app
# Adding github to known hosts
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts 
RUN --mount=type=ssh,id=github git clone git@github.com:xodix/smoll-server.git .
RUN make

FROM scratch
LABEL org.opencontainers.image.authors="Bartłomiej Deska"
LABEL org.opencontainers.image.title="SMOLL-HTTP"
LABEL org.opencontainers.image.description="Very small http server for a contest"
EXPOSE 3000

COPY --from=build /app/server ./
HEALTHCHECK --interval=10s --timeout=5s CMD ["/server", "healthcheck"]

ENTRYPOINT [ "/server" ]
